# build with the following command
# sudo docker build -f Dockerfile_workshop_jupyter -t openmcworkshop/workshop_jupyter . --no-cache

FROM openmcworkshop/openmc_workshop_dependencies:openmc_dagmc_nndc_dependencies

RUN git clone https://github.com/ukaea/openmc_workshop

WORKDIR /openmc_workshop

RUN git checkout jupyter


CMD ["jupyter", "lab", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]